/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database connectivity check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is reachable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in member
         * @description Returns identity, membership level, roles, and public profile. Sensitive stores (contact details, emergency contacts, dietary, medical) are deliberately not included here; each is served by its own endpoint so their narrower audiences stay enforced.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in member. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Viewer"];
                    };
                };
                /** @description Not signed in. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "up" | "down";
            uptimeSeconds: number;
        };
        Viewer: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** Format: uri */
            image: string | null;
            membershipLevel: components["schemas"]["MembershipLevel"];
            roles: components["schemas"]["Role"][];
            profile: components["schemas"]["Profile"];
        };
        /** @enum {string} */
        MembershipLevel: "foe" | "member";
        /** @enum {string} */
        Role: "sister" | "officer" | "captain" | "triad" | "medical" | "money" | "web" | "kitchen";
        Profile: {
            userId: string;
            scaName: string | null;
            pronouns: string | null;
            city: string | null;
            state: string | null;
            bio: string | null;
        } | null;
        Error: {
            error: {
                /** @example unauthorized */
                code: string;
                /** @example Sign in to continue. */
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
